<?php

/**
 * @file
 */

use Drupal\app\Form\Account\AccountProfileForm;
use Drupal\app\Form\Account\AccountSettingsForm;

/**
 * Implements hook_entity_type_build().
 */
function app_entity_type_build(array &$entity_types) {
  if (isset($entity_types['user'])) {
    $entity_types['user']->setFormClass('settings', AccountSettingsForm::class);
    $entity_types['user']->setFormClass('profile', AccountProfileForm::class);
  }
}

/**
 * hook_theme().
 */
function app_theme($existing, $type, $theme, $path) {
  return [
    'page_404' => [
      'variables' => ['title' => NULL],
      'template' => '404',
      'path' => $path . '/templates/4xx',
    ],
  ];
}
